-- MySQL Script generated by MySQL Workbench
-- Sun Feb 15 20:16:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coffe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `coffe` ;

-- -----------------------------------------------------
-- Table `coffe`.`informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`informacion` (
  `inf_id` VARCHAR(50) NOT NULL,
  `inf_nombre` VARCHAR(45) NULL,
  `inf_descripcion` VARCHAR(45) NULL,
  `inf_img` VARCHAR(45) NULL,
  PRIMARY KEY (`inf_id`),
  UNIQUE INDEX `inf_id_UNIQUE` (`inf_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`usuario` (
  `usu_id` VARCHAR(45) NOT NULL,
  `usu_usuario` VARCHAR(45) NOT NULL,
  `usu_contrasena` VARCHAR(45) NOT NULL,
  `usu_rol` ENUM('0','1','2','3') NULL DEFAULT '0',
  PRIMARY KEY (`usu_id`),
  UNIQUE INDEX `usu_id_UNIQUE` (`usu_id` ASC),
  UNIQUE INDEX `usu_usuario_UNIQUE` (`usu_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`categoria_producto` (
  `cp_id` VARCHAR(45) NOT NULL,
  `cp_nombre` VARCHAR(45) NOT NULL,
  `cp_descripcion` VARCHAR(45) NULL,
  `cp_fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`cp_id`),
  UNIQUE INDEX `cp_id_UNIQUE` (`cp_id` ASC),
  UNIQUE INDEX `cp_nombre_UNIQUE` (`cp_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`producto` (
  `pro_id` VARCHAR(45) NOT NULL,
  `pro_nombre` VARCHAR(45) NULL,
  `pro_descripcion` VARCHAR(45) NULL,
  `pro_img` VARCHAR(45) NULL,
  `pro_precio` DOUBLE NOT NULL DEFAULT 0.0,
  `pro_existe` ENUM('0','1') NOT NULL DEFAULT '1',
  `pro_genera_iva` ENUM('0','1') NOT NULL,
  `pro_fecha_creacion` DATE NOT NULL,
  `categoria_producto_cp_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pro_id`),
  UNIQUE INDEX `pro_id_UNIQUE` (`pro_id` ASC),
  UNIQUE INDEX `pro_nombre_UNIQUE` (`pro_nombre` ASC),
  INDEX `fk_producto_categoria_producto1_idx` (`categoria_producto_cp_id` ASC),
  CONSTRAINT `fk_producto_categoria_producto1`
    FOREIGN KEY (`categoria_producto_cp_id`)
    REFERENCES `coffe`.`categoria_producto` (`cp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`ingrediente` (
  `ing_id` VARCHAR(45) NOT NULL,
  `ing_nombre` VARCHAR(45) NOT NULL,
  `ing_descripcion` VARCHAR(45) NULL,
  `ing_img` VARCHAR(45) NULL,
  `ing_fecha_creacion` DATE NULL,
  `ing_existe` ENUM('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`ing_id`),
  UNIQUE INDEX `ing_id_UNIQUE` (`ing_id` ASC),
  UNIQUE INDEX `ing_nombre_UNIQUE` (`ing_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`pedido` (
  `ped_id` VARCHAR(45) NOT NULL,
  `ped_codigo` VARCHAR(45) NULL,
  `ped_fecha_creacion` DATE NOT NULL,
  `ped_pagado` ENUM('0','1') NULL DEFAULT '0',
  `usuario_usu_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ped_id`),
  UNIQUE INDEX `ped_id_UNIQUE` (`ped_id` ASC),
  UNIQUE INDEX `ped_codigo_UNIQUE` (`ped_codigo` ASC),
  INDEX `fk_pedido_usuario1_idx` (`usuario_usu_id` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `coffe`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`pedido_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`pedido_has_producto` (
  `pp_id` VARCHAR(45) NOT NULL,
  `pedido_ped_id` VARCHAR(45) NOT NULL,
  `producto_pro_id` VARCHAR(45) NOT NULL,
  `pp_estado` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`pp_id`),
  UNIQUE INDEX `pp_id_UNIQUE` (`pp_id` ASC),
  INDEX `fk_producto_idx` (`producto_pro_id` ASC),
  INDEX `fk_pedido_idx` (`pedido_ped_id` ASC),
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`pedido_ped_id`)
    REFERENCES `coffe`.`pedido` (`ped_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`producto_pro_id`)
    REFERENCES `coffe`.`producto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`categoria_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`categoria_entrada` (
  `ce_id` VARCHAR(50) NOT NULL,
  `ce_nombre` VARCHAR(45) NOT NULL,
  `ce_descripcion` VARCHAR(45) NULL,
  `ce_fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`ce_id`),
  UNIQUE INDEX `ic_id_UNIQUE` (`ce_id` ASC),
  UNIQUE INDEX `ce_nombre_UNIQUE` (`ce_nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coffe`.`entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffe`.`entrada` (
  `ent_id` VARCHAR(45) NOT NULL,
  `ent_valor` DOUBLE NULL DEFAULT 0.0,
  `ent_fecha_creacion` DATE NULL,
  `usuario_usu_id` VARCHAR(45) NOT NULL,
  `categoria_entrada_ce_id` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ent_id`),
  UNIQUE INDEX `ent_id_UNIQUE` (`ent_id` ASC),
  INDEX `fk_entrada_usuario1_idx` (`usuario_usu_id` ASC),
  INDEX `fk_entrada_categoria_entrada1_idx` (`categoria_entrada_ce_id` ASC),
  CONSTRAINT `fk_entrada_usuario1`
    FOREIGN KEY (`usuario_usu_id`)
    REFERENCES `coffe`.`usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_categoria_entrada1`
    FOREIGN KEY (`categoria_entrada_ce_id`)
    REFERENCES `coffe`.`categoria_entrada` (`ce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
